# -*- coding: utf-8 -*-
"""Programa_5_diccionarios_josua.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tPaC87H0aOGD2NYvJ0DVeZMkoAUbfor2
"""

class Persona:
    def __init__(self):
        # Diccionario con los datos personales
        self.datos = {
            "Nombre": "Juan Pérez",
            "Matricula": "A001",
            "Edad": 18,
            "Peso": 70,
            "Telefono": "555-123-456",
            "Domicilio": "Calle Falsa 123",
            "Carrera": "Ingeniería en Sistemas"
        }

    # Método para mostrar todos los datos
    def imprimir_datos(self):
        for clave in self.datos:
            print(clave, ":", self.datos[clave])

    # Método para modificar un dato
    def actualizar(self, clave, valor):
        if clave in self.datos:
            self.datos[clave] = valor
            print(f"{clave} cambiado a: {valor}")
        else:
            print("Esa clave no existe")


p = Persona()

# Mostrar todos los datos
p.imprimir_datos()

# Acceder directamente a un dato del diccionario
print("\nNombre:", p.datos["Nombre"])

# Modificar un dato
p.actualizar("Edad", 19)

# Mostrar de nuevo los datos
p.imprimir_datos()
