# -*- coding: utf-8 -*-
"""Programa_6_Operaciones_con_listas_josua.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJPUqH9R5vWnsIlMskAhXTX1lyPzqiLk
"""

# Fórmula: °C = (°F - 32) * 5/9
class Estacion:
    def __init__(self):
        self.temp_f = [80, 72, 95, 82, 79, 72, 85]
        self.temp_c = []

    def convertir(self):
        for f in self.temp_f:
            c = (f - 32) * 5/9
            self.temp_c.append(round(c, 2))

    def mostrar(self):
        print("\nTemperaturas en Fahrenheit:")
        for i, f in enumerate(self.temp_f):
            print(f"Hora {i+1}: {f} °F")

        print("\nTemperaturas en Centígrados:")
        for i, c in enumerate(self.temp_c):
            print(f"Hora {i+1}: {c} °C")

e = Estacion()
e.convertir()
e.mostrar()